var json_pemerintahan_3 = {
"type": "FeatureCollection",
"name": "pemerintahan_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "NAMOBJ": "UPT Balai Penyuluhan Pertanian Sandaran", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.499093, 0.827691 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "KUA Kecamatan Sandaran", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.495517, 0.832649 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Manubar", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.496033, 0.832877 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "UPT Dinas Pendidikan Sandaran", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.49363, 0.834272 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Susuk Dalam", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.216061, 0.916709 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Lembaga Pemberdayaan Masyarakat Adat dan P*", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.199018, 0.876283 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Susuk Luar", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.198988, 0.876159 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Badan Permusyawaratan Desa Susuk Luar", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.19934, 0.876214 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Lembaga Adat Marukangan", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.327846, 0.878675 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Marukangan", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.325191, 0.864183 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Sandaran", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.866454, 0.880537 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Karang Taruna Tanjungmangkalihat", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.978732, 1.007323 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Tanjungmangkalihat", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.979, 1.004101 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Badan Permusyawaratan Desa Tanjungmangkalihat", "FGSGOV": "999", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Pemerintah Lainnya", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.979013, 1.003772 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kepolisian Sektor Sandaran", "FGSGOV": "16", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Polisi", "SRS_ID": null, "LCODE": "GK0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.968103, 1.033793 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Camat Sandaran", "FGSGOV": "9", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Camat", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.497607, 0.831795 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "Kantor Kepala Desa Tadoan", "FGSGOV": "10", "LUAS": 0.0, "FCODE": null, "REMARK": "Kantor Kepala Desa", "SRS_ID": null, "LCODE": "GD0020", "METADATA": null }, "geometry": { "type": "Point", "coordinates": [ 118.547358, 0.990242 ] } }
]
}
